/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package DSA;

import javax.swing.table.DefaultTableModel;
import sun.io.Converters;

/**
 *
 * @author Thwaraka Yogarajah
 */
public class MyMain extends javax.swing.JFrame {
   BinaryTree tree = new BinaryTree();

    /**
     * Creates new form MyMain
     */
    public MyMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewBook = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtInsertISBNNo = new javax.swing.JTextField();
        jtxtInsertBookName = new javax.swing.JTextField();
        jtxtInsertAuthorName = new javax.swing.JTextField();
        jtxtAuthorSurName = new javax.swing.JTextField();
        jbtnInsertSave = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jtxtSerachText = new javax.swing.JTextField();
        jbtnSearch = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtSearchISBNNo = new javax.swing.JTextField();
        jtxtSearchBookName = new javax.swing.JTextField();
        jtxtSearchAuthorName = new javax.swing.JTextField();
        jtxtSearchAuthorSurName = new javax.swing.JTextField();
        jbtnDelete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbtnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ISBN No");

        jLabel2.setText("Book Name");

        jLabel3.setText("Author Name");

        jLabel4.setText("Author SurName");

        jbtnInsertSave.setText("Save");
        jbtnInsertSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInsertSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtInsertISBNNo)
                    .addComponent(jtxtInsertBookName)
                    .addComponent(jtxtInsertAuthorName)
                    .addComponent(jtxtAuthorSurName, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addContainerGap(283, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnInsertSave)
                .addGap(128, 128, 128))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtInsertISBNNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtInsertBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtInsertAuthorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtAuthorSurName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(jbtnInsertSave)
                .addGap(63, 63, 63))
        );

        NewBook.addTab("New Book", jPanel1);

        jbtnSearch.setText("Search");
        jbtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchActionPerformed(evt);
            }
        });

        jLabel5.setText("ISBN No");

        jLabel6.setText("Book Name");

        jLabel7.setText("Author Name");

        jLabel8.setText("Author SurName");

        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jtxtSerachText, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnSearch))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtSearchISBNNo, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(jtxtSearchBookName)
                            .addComponent(jtxtSearchAuthorName)
                            .addComponent(jtxtSearchAuthorSurName))))
                .addGap(223, 223, 223))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtnDelete)
                .addGap(87, 87, 87))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtSerachText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSearch))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtSearchISBNNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtSearchBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtSearchAuthorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtxtSearchAuthorSurName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jbtnDelete)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        NewBook.addTab("Search & Delete", jPanel2);

        jbtnRefresh.setText("Refresh");
        jbtnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRefreshActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ISBN No", "Book Name", "Author Name", "Author Surname"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(572, Short.MAX_VALUE)
                .addComponent(jbtnRefresh)
                .addGap(35, 35, 35))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnRefresh)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        NewBook.addTab("View All", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NewBook)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NewBook)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnInsertSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInsertSaveActionPerformed
   
   tree.add(Integer.parseInt(jtxtInsertISBNNo.getText()),jtxtInsertBookName.getText(),jtxtInsertAuthorName.getText(),jtxtAuthorSurName.getText());
        
        System.out.println("Entering Book Details ======================================");
        tree.print(Integer.parseInt(jtxtInsertISBNNo.getText()));//Console Only
        System.out.println("============================================================");
        System.out.println("");
        System.out.println("Current Tree ===============================================");
        tree.print();//Console Only
        System.out.println("============================================================");
        
        jtxtInsertISBNNo.setText("");
        jtxtInsertBookName.setText("");
        jtxtInsertAuthorName.setText("");
        jtxtAuthorSurName.setText("");
   
    }//GEN-LAST:event_jbtnInsertSaveActionPerformed

    private void jbtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchActionPerformed
        
		jtxtSearchISBNNo.setText("");
        jtxtSearchBookName.setText("");
        jtxtSearchAuthorName.setText("");
        jtxtSearchAuthorSurName.setText("");
        
        Node node = tree.searchByISBNNo(Integer.parseInt(jtxtSerachText.getText()));
        jtxtSearchISBNNo.setText(Integer.toString(node.isbn));
        jtxtSearchBookName.setText(node.title);
        jtxtSearchAuthorName.setText(node.auther);
        jtxtSearchAuthorSurName.setText(node.surname);
        
        System.out.println("Current Tree ===============================================");
        tree.print(Integer.parseInt(jtxtSearchISBNNo.getText()));//Console Only
        System.out.println("============================================================");
        
    }//GEN-LAST:event_jbtnSearchActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        
		 tree.delete(Integer.parseInt(jtxtSearchISBNNo.getText()));
        System.out.println("Current Tree ===============================================");
        tree.print();//Console Only
        System.out.println("============================================================");
		
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRefreshActionPerformed
        Node fullNode = tree.getRoot();
        printLevelOrderDFS(fullNode);
    }//GEN-LAST:event_jbtnRefreshActionPerformed
    
	public void printLevelOrderDFS(Node root) {
	    	
	        int height = maxHeight(root);
	        for (int i = 0; i < height; i++) {
	        	
	        	double indent = ((Math.pow(2, height-(i+1))-1)*2);
	        	
	        	for(int y =0;y<indent; y++ ){
	     
	        		
	        	}
	            printLevel(root, i , indent);
	            
	        }
	    }
	    
    public void printLevel(Node node, int level,double height) {
	    		    	int k = 0;
	        if (node == null) {
	        	for(int i = 0 ; i< (height*2) ; i++ ){
	        		}
	            return;
	        }
	        if (level == 0) 
                {
                    //jTable1.getModel().setValueAt("Book Name",k,5);
                    
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                    model.addRow(new Object[]{node.isbn,node.title,node.auther,node.surname});
                    
	            System.out.print(" "+node.isbn+" ");
	            System.out.print(" "+node.title+" ");
                    System.out.print(" "+node.auther+" ");
                    System.out.print(" "+node.surname+" ");
                    System.out.println("");
                    k++;
                    
                    for(int i = 0 ; i< (height*2) ; i++ ){
	        		}
	            
	        } if(level == 1){
	        	
	        }
	        if (level != 0) {
	            printLevel(node.leftChild, level - 1,height);
	            printLevel(node.rightChild, level - 1,height);
	        }	        
	    }
	    
	    public int maxHeight(Node root) {
	        if (root == null) {
	            return 0;
	        }
	        return 1 + Math.max(maxHeight(root.leftChild), maxHeight(root.rightChild));
	    }
	
	
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyMain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane NewBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnInsertSave;
    private javax.swing.JButton jbtnRefresh;
    private javax.swing.JButton jbtnSearch;
    private javax.swing.JTextField jtxtAuthorSurName;
    private javax.swing.JTextField jtxtInsertAuthorName;
    private javax.swing.JTextField jtxtInsertBookName;
    private javax.swing.JTextField jtxtInsertISBNNo;
    private javax.swing.JTextField jtxtSearchAuthorName;
    private javax.swing.JTextField jtxtSearchAuthorSurName;
    private javax.swing.JTextField jtxtSearchBookName;
    private javax.swing.JTextField jtxtSearchISBNNo;
    private javax.swing.JTextField jtxtSerachText;
    // End of variables declaration//GEN-END:variables
}
